version: 2
save-node: &save-node
  save_cache:
    name: Save node modules cache
    key: node_modules-{{ checksum "package-lock.json" }}
    paths:
      - node_modules
restore-node: &restore-node
  restore_cache:
    name: Restore node_modules cache
    key: node_modules-{{ checksum "package-lock.json" }}
save-git: &save-git
  save_cache:
    name: Save git cache
    key: code-{{ .Revision }}
    paths:
      - .git
      - ~/.ssh
restore-git: &restore-git
  restore_cache:
    name: Restore git cache
    key: code-{{ .Revision }}
workflows:
  version: 2
  all:
    jobs:
      - node-latest
      - node8:
          requires:
            - node-latest
      - release:
          filters:
            branches:
              only: master
          requires:
            - node-latest
            - node8
jobs:
  local-test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm run verify
  node-latest:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - <<: *restore-node
      - run:
          name: Install Dependencies
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - run:
          name: update greenkeeper lockfile
          command: ./node_modules/.bin/greenkeeper-lockfile-update
      - <<: *save-node
      - <<: *save-git
      - run: npm run verify-ci
      - run: npx codecov
      - store_test_results:
          path: .reports/junit
  node8:
    docker:
      - image: 'circleci/node:8'
    steps:
      - <<: *restore-git
      - <<: *restore-node
      - run: npm run verify-ci
  release:
    docker:
      - image: circleci/node:10
    steps:
      - <<: *restore-git
      - <<: *restore-node
      - run: npm run build
      - run:
          name: upload greenkeeper lockfile
          command: ./node_modules/.bin/greenkeeper-lockfile-upload
      - run: npx semantic-release
