version: 2
workflows:
  version: 2
  all:
    jobs:
      - node-latest
      - node11:
          requires:
            - node-latest
      - node10:
          requires:
            - node-latest
      - node8:
          requires:
            - node-latest
      # - release:
      #     filters:
      #       branches:
      #         only: master
      #     requires:
      #       - node-latest
      #       - node11
      #       - node10
      #       - node8
jobs:
  local-test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm run verify
  node-latest:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules cache
          key: yarn-{{ checksum "yarn.lock" }}
      - run: yarn
      # - run: yarn bootstrap
      - run: yarn commitlint-circle
      - run: yarn lint
      - run: yarn build
      - run: yarn depcheck
      - run: yarn test:nodejs --coverage --maxWorkers=2
      # - run: yarn codecov
      - store_test_results:
          path: .reports/junit
      - save_cache:
          name: Save node modules cache
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - packages/*/node_modules
      # - persist_to_workspace:
      #     root: '.'
      #     paths:
      #       - node_modules
      #       - ./packages/*/.ts/*
      #       - ./packages/*/dist/*
      #       - ./packages/*/lib/*
      #       - ./packages/*/libm/*
  node11:
    docker:
      - image: 'circleci/node:11'
    steps:
      - checkout
      # - attach_workspace:
      #     at: '.'
      - run: yarn
      # - run: yarn bootstrap
      - run: yarn build
      - run: yarn test:nodejs --coverage --maxWorkers=2
      - store_test_results:
          path: .reports/junit
  node10:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      # - attach_workspace:
      #     at: '.'
      - run: yarn
      - run: yarn build
      - run: yarn test:nodejs --coverage --maxWorkers=2
      - store_test_results:
          path: .reports/junit
  node8:
    docker:
      - image: 'circleci/node:8'
    steps:
      - checkout
      # - attach_workspace:
      #     at: '.'
      - run: yarn
      - run: yarn build
      - run: yarn test:nodejs --coverage --maxWorkers=2
      - store_test_results:
          path: .reports/junit
  release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      # - attach_workspace:
      #     at: '.'
      - run: git config user.email $GIT_CONFIG_EMAIL
      - run: git config user.name $GIT_CONFIG_NAME
      - run: yarn
      - run: yarn build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run: yarn release
