name: CI

on:
  push:
    branches:
      - vnext
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/npm@master
    - run: yarn
    - run: yarn bootstrap
    - run: yarn commitlint-circle
    - run: yarn lint
    - run: yarn build
    - run: yarn depcheck
    - run: yarn coverage --maxWorkers=2
