name: release
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - beta
jobs:
  code:
    uses: ./.github/workflows/pnpm-verify-cross-platform.yml
  release:
    uses: mocktomata/.github/.github/workflows/pnpm-release-changeset.yml@main
    needs: code
    secrets: inherit
